name: Test Author Service

on:
  push:
    branches:
      - "*"
    paths:
      - "author_service/**"
      - "common/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:

  test_autor_service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Initialize Go Environment
        run: go mod tidy

      - name: Run Tests
        run: go test -coverprofile=cover.out ./author_service/...

      - name: Report test-coverage to Codacy
        run: |
          # Install the CLI
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          --force-coverage-parser go -r ./cover.out